services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: marketcove_db
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: changeit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: